@startuml

package UserManagement {
    entity Customer {
        * ID
        --
        login
        passwordHash
        name
        phoneNumber
        email
        * primaryAddressID
    }

    entity Address {
        * ID
        --
        * customerID
        * name
        * city
        * street
        * building
        entrance
        floor
        room
    }
}

package CentralCatalog {
    entity Product {
        * ID
        --
        imageUrl
        name
        averageStars
    }

    entity ProductRating {
        * productID
        * customerID
        --
        stars
    }

    entity Attribute {
        * ID
        --
        name
    }

    entity ProductAttribute {
        * productID
        * attributeID
        --
        value
    }
}

package "LocalStore #8" {
    entity "Product" as LocalProduct {
        * ID
        --
        * sku
        * barcode
        imageUrl
        * name
        averageStars
        * catalogEntryLeftIndex
        * **available**
        * quantum
        * measure
        * basePrice
    }

    note right of LocalProduct {
        Products are synced with CentralCatalog
        on daily basis. However it can't be deleted
        from the local store to keep DB consistency
    }

    note left of LocalProduct {
        Base price without increases and discounts.
        Comes when catalog is being imported
    }

    entity "Customer" as LocalCustomer {
        * ID
        --
    }

    entity "ProductRating" as LocalProductRating {
        * productID
        * customerID
        --
        stars
    }

    note bottom of LocalProductRating {
        Accumulates product ratings.
        To be sent to CentralCatalog nightly.
        Application accept all the clicks on rating,
        but accept only unique records asynchronously.
        Product.averageStars field is to be
        recalculated every N hours
    }

    entity "Attribute" as LocalAttribute {
        * ID
        --
        name
        type
    }

    entity "ProductAttribute" as LocalProductAttribute {
        * productID
        * attributeID
        --
        value
    }

    entity "CatalogEntry" as LocalCatalogEntry {
        * leftIndex
        * rightIndex
        --
        * name
        * depth
        code
    }

    note bottom of LocalCatalogEntry  {
        Nested set model
    }

    entity "LineItem" as LocalLineItem {
        * productID
        * basketID
        --
        * price
        * quantity
        * status
    }

    note bottom of LocalLineItem {
        Price is to be calculated
        at the moment order is being created.
        See GroupPriceRule & CatalogPriceRule
    }

    entity "Basket" as LocalBasket {
        * ID
        --
        * customerID
        * status
    }

    entity "Order" as LocalOrder {
        * basketID
        --
        * customerID
        * status

    }

    entity "DeliveryAddress" as LocalDeliveryAddress {
        * basketID
        --
        * name
        * city
        * street
        * building
        entrance
        floor
        room
    }

    note bottom of LocalDeliveryAddress {
        A copy of customer's address
        which is taken at the same time
        when order is being created
    }

    entity "CatalogPriceRule" as LocalCatalogPriceRule {
        ID
        --
        catalogEntryLeftIndex
        priority
        percent
    }

    note left of LocalCatalogPriceRule {
        LineItem.price = Product.basePrice + Product.basePrice * percent / 100
    }

    entity "GroupPriceRule" as LocalGroupPriceRule {
        ID
        --
        groupNumber
        priority
        percent
    }

    note left of LocalGroupPriceRule {
        LineItem.price = Product.basePrice + Product.basePrice * percent / 100
    }

    entity "ProductGroup" as LocalProductGroup {
        groupNumber
        productID
        --
    }

    LocalProduct ||--o{ LocalProductRating
    LocalProduct ||--o{ LocalProductAttribute
    LocalProductAttribute }o--|| LocalAttribute
    LocalCustomer ||..o{ LocalProductRating
    LocalProduct }o--|| LocalCatalogEntry
    LocalOrder |o--|| LocalBasket
    LocalOrder |o..|| LocalCustomer

    LocalBasket }o..|| LocalCustomer
    LocalBasket ||--o{ LocalLineItem
    LocalLineItem }o--|| LocalProduct
    LocalOrder ||--|| LocalDeliveryAddress

    LocalProductGroup ||--|{ LocalProduct
    LocalGroupPriceRule ||--|| LocalProductGroup
    LocalCatalogPriceRule ||--|| LocalCatalogEntry
}

Product ||--o{ ProductRating
Product ||--o{ ProductAttribute
ProductAttribute }o--|| Attribute
Customer ||..o{ ProductRating
Customer ||--|{ Address


package Example {
    One ||..|{ OneOrMany
    One ||..o| ZeroOrOne
    One ||--o{ ZeroOrMany

    entity EntityExample {
        * identifying_attribute
        --
        * mandatory_attribute
        optional_attribute
    }
}
@enduml